### ISSUE TITLE
Cannot run nEXT from source

### ISSUE THREAD

**Issue by hiroki802** [nEXT-Browser/nEXT#12]
I'm trying to load the system of nEXT and do some coding on Emacs.
I put the source code in the local project folder of quicklisp and did as below. 

```
(ql:quickload :next)
(next:start)

```
After loading the system and calling the start function, 
the browser comes up, but I cannot load URL in tab with C-l.
https://gyazo.com/b86cc7d9fb6d645808695ad6b9f79fdf

My environment is:
　OS: macOS 10.13.1 High Sierra
　CCL:  Version 1.11-r16635  (DarwinX8664)

**Comment by jmercouris** [comment]
Hi @hiroki802 Thank you for your report and interest! This has to do with the way events are dispatched into the system. I'm working on a way to get key-events working in the REPL.

1. If you look at the `next.asd` file you'll notice a `require cocoa`. This loads the objective-c bridge and Cocoa / the Cocoa-IDE. The Cocoa IDE has an instance of NSApplication.

2. In order to capture all events sent to a Cocoa Application, one has to subclass NSApplication and implement the method sendEvent:.

3. Therefore, I create a subclass of NSApplication, please see cocoa/application.lisp

```
(defclass next-application (ns:ns-application) ()
  (:metaclass ns:+ns-application))

(objc:defmethod (#/sendEvent: :void) ((self next-application) event)
  (if (eql #$NSKeyDown (#/type event))
      (unless (interface:process-event event)
	(call-next-method event))
      (call-next-method event)))
```

4. The subclass of NSApplication is set during compilation of standalone nEXT in `application.lisp` on the section that says

```
      (let* ((appclass next-application)
	     (app (#/sharedApplication appclass)))

```
 
5. In order to work with the repl therefore and capture all keystroke events, one has to figure out a way to start the cocoa ide with a custom subclass of NSApplication. I have had a discussion about this topic with Pascal (pjb) on IRC. Please see: https://ccl.clozure.com/irc-logs/ccl/ccl-2017-11.txt. Please see the messages starting at: 2017-11-13T17:44:33Z


Thank you in advance for any thoughts! I've been working on this exact problem as it is such a pain in order to compile to test things from the user interface. Of course I could very easily alter the sources of CCL to make this work, but I want to make it VERY EASY for the user to run the application without having to do that. 


One solution that I did come up with was by implementing:

```
(objc:defmethod (#/sendEvent: :void) ((self ns:ns-application) event)
  (if (eql #$NSKeyDown (#/type event))
      (unless (interface:process-event event)
	(call-next-method event))
      (call-next-method event)))
```

This does allow the capturing of all events, but the compiler complains a little bit when loading this function, you can accept the complain and the program will work as normal, but Objective-C doesn't particularly like runtime redefinition of methods (this is called swizzling). 



Thank you for any feedback/help!!! PRs/suggestions welcome!

**Comment by hiroki802** [comment]
Hi. Thank you for your reply!
How should I call the sendEvent method?
I guess ...
(#/sendEvent: bra bra) on REPL.

**Comment by jmercouris** [comment]
Hi Hiroki802,

One should not directly invoke the sendEvent method. NSApplication comes with a default implementation of sendEvent. This method is invoked every time an event occurs on screen. Our challenge is this:


1. How can we use our own class next-event, which subclasses NSEvent within the REPL.


2. How can we do this without modifying the sources of CCL?


Thank you!

**Comment by jmercouris** [comment]
Hi @hiroki802 I have great news. I was finally able to solve this issue in an extremely simple way please see the commit here: https://github.com/nEXT-Browser/nEXT/commit/a9d768eacb309307a5f0c26d00465be9d5ee0aad

Please try it and let me know how everything works! Thanks!

**Comment by hiroki802** [comment]
It works ! I took a screenshot and uploaded it on Youtube:
https://youtu.be/Dz15-k0BOJY

**Comment by jmercouris** [comment]
Thank you for the video! You have no idea how excited I was to see someone using nEXT!!!
