### ISSUE TITLE
[SUGGESTION] Additional repository or document for user customisations/extensions

### ISSUE THREAD

**Issue by cmacrae** [nEXT-Browser/nEXT#20]
This is such a cool project! 🕶   

Of course, it's immediately clear to anyone familiar with Lisp extensible platforms (like Emacs) that this is the real strength of nEXT.  

I know it's early days, but I think it'd be great to put together a place that people can share, discuss, suggest their customisations and extensions.  

I don't know if it would really warrant a new repository, or maybe it'd just be easier to have a markdown doc.  

Thanks so much for sharing your work - I'm really looking forward to seeing where nEXT goes 🙂

**Comment by jmercouris** [comment]
Hi, thank you for your patience! I've just made a document here: https://github.com/nEXT-Browser/nEXT/blob/master/documents/EXTENSION.org

If you wish to add something, please feel free to do so! I've added a couple of examples to get us started, but as of right now, I do not have much in the way of customization, because I have more or less configured nEXT exactly as I would use it :D
