### ISSUE TITLE
Fails to compile on ccl Version 1.11-r16635  (DarwinX8632)

### ISSUE THREAD

**Issue by ngksternhagen** [nEXT-Browser/nEXT#25]
I am trying to compile nEXT from source on OSX 10.11.6 by following the directions in https://github.com/nEXT-Browser/nEXT/tree/master/next#macos-instructions. It seems that due to user error or a problem in the build config the "QL" package can't be found.

```
$ ccl --version
Version 1.11-r16635  (DarwinX8632)
```

```
$ ccl --no-init --load make.lisp
> Error: There is no package named "QL" .
> While executing: CCL::%PARSE-TOKEN, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry finding package with name "QL".
> Type :? for other options.

```
I have (I believe) exactly followed the quicklisp installation instructions presented in https://github.com/nEXT-Browser/nEXT/tree/master/next#macos-instructions

I am not an experienced quicklisp user so it's possible and even likely that I am doing something insane.

I am happy to paste the content of files from my ~/quicklisp/ if that would be helpful.

**Comment by jmercouris** [comment]
Hi, thank you for your very detailed report! The issues you are probably facing are most likely related to the first few lines of the script:

```
(let ((quicklisp-init (merge-pathnames ".quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
```

If that directory doesn't exist, or if your `quicklisp/setup.lisp` file is located in a different directory you'll have to update the build script. So In your case if you have a `~/quicklisp/`, then you can check to see if you have a `~/quicklisp/setup.lisp` file, and you should be good to go!


As another question, are you able to normally `(ql:quickload "some-package")` while in slime?

**Comment by seanfarley** [comment]
I ran into this issue as well. Since the normal install of quicklook.lisp adds itself to `~/.ccl-init.lisp` removing `--no-init` fixed it for me. I realize that removing that option would probably cause more harm than not.

Thanks to this thread, though, I was able to hide `~/quicklook` from my home directory; so there's that :-)

**Comment by jmercouris** [comment]
Due to lack of update/quicklisp fix for some users, I will be closing this issue.

As a note to future readers: the ideal solution is not removing --no-init, but rather changing the make.lisp script to load quicklisp properly by pointing it to the correct directory on your system. At the time of this writing, the make.lisp script needs to be updated to handle the potential install locations of quicklisp.
