### ISSUE TITLE
nEXT inside a emacs-buffer?

### ISSUE THREAD

**Issue by cjohansson** [nEXT-Browser/nEXT#44]
I would love having nEXT inside a emacs-buffer, is it possible? If not, would it be possible in the future?

**Comment by jmercouris** [comment]
Hi Christian, thank you for your question! Yes, it is technically possible, and only on Linux, using something like the XWidgets (I think that’s what it’s called) support in Emacs. This allows you to have an X Application as a buffer. This is of course not ideal. Instead, if on Linux, I would recommend something like Stump WM. If you are on MacOS, as far as I know this will not be easily possible. Thank you for your interest!

-John

**Comment by cjohansson** [comment]
Ok thanks will check that out :-)

**Comment by seanfarley** [comment]
Just a note that there is some experimental work for getting xwidgets (well, webkit) in an emacs buffer in macos: https://github.com/veshboo/emacs

I've also done some work to get that to work in Mituharu's macos port of emacs as well: https://bitbucket.org/mituharu/emacs-mac/pull-requests/1/rfc-add-xwidget-implementation/diff

That being said, I'm not sure the emacs approach is really suitable or even a goal of this project (I'd be interested to hear back on that, though).

**Comment by jmercouris** [comment]
Hey Sean, that is some amazing stuff! I had no idea that was even remotely possible! The emacs approach is not a goal of this project, though I’m not heavily against it if someone wants to integrate it. I imagine if you have just webkit working, and since there is now an X version of nEXT, it should be possible to also run nEXT within a buffer. That may be confusing to have buffers within buffers though.

**Comment by seanfarley** [comment]
Oh, yeah, that sounds promising! Having an external API and/or one-buffer makes a lot of sense. I'll have to check back when I have a bit more time to dig around with all of this.
