### ISSUE TITLE
Feature Request: refresh page

### ISSUE THREAD

**Issue by cjohansson** [nEXT-Browser/nEXT#47]
I can't see this feature in the manual, maybe it exists?

I think it would be **emacsy** to bind it to *g*

**Comment by jmercouris** [comment]
Hello! Yes, this feature already exists, but in a non-obvious way, `C-l` will load the current-url into the minibuffer, then pressing `RET` will simply load that page, effectively reloading it

Of course, as with everything emacsy, the best would be to offer several ways of doing this for the end user, for now if you want you can make a very simple Parenscript within your init function that will allow you to reload the page

```
(defparenstatic reload-page
    (ps:chain location (reload)))
```

then, you can bind it to whatever you like. If you want to bind reload the page to something like "g", you will have problems when you want to type "g" into an input box, the system will reload the page instead of letting you type "g".

To compensate for this, you'd then have to make an "insert-mode" for inputting text that has no keybindings on a normal typed letter. E.g. you'd be getting into `EVIL` territory. This is currently possible of course, you could write your own `EVIL` mode right now. For a simple example of how to write a mode please see https://github.com/nEXT-Browser/nEXT/blob/master/documents/EXTENSION.org#running-shell-commands-within-next in which I've defined a "shell-mode".

Once again, thank you for your interest and opening the issue! I am always trying to make the software better for the users, and feedback like this is always very valuable. My own use case of course does not cover the myriad of other ones, so I really appreciate this, thank you!

**Comment by cjohansson** [comment]
Ok thanks, `C-l` + `RET` works, I didn't think about the issue with input fields. I will try to get into the customizing business 8-)
