### ISSUE TITLE
Sierra release?

### ISSUE THREAD

**Issue by asimpson** [nEXT-Browser/nEXT#5]
The project is currently building for High Sierra (10.13). Any chance we can get a release built for 10.12?

**Comment by patricksimpson** [comment]
👍

**Comment by jmercouris** [comment]
Hi, I'm afraid not, as I've already installed High Sierra on my machine, I don't know of any other way to build a backwards compatible release, sorry! I'll leave this open in case anyone who has a Sierra machine is willing to produce a build- I can give whoever it is guidance on how to do so.

**Comment by dhruska** [comment]
@jmercouris I got you - if you can give me instructions I'm happy to produce a build.

**Comment by jmercouris** [comment]
@dhruska Thank you for the offer. More or less you have to start with getting the developer build to work:  https://github.com/nEXT-Browser/nEXT/tree/master/next#osx-instructions

Then afterwards, I can update the compile instructions, I will have to run some tests on the new eql/ecl versions. It is a little more complex than simply deploying due to upstream fixes.

**Comment by can3p** [comment]
For my app I was able to setup an automatic travis build that attached image to release, maybe something similar can be done for the nEXT? In my case it was an electron app, however build machine is mac, so I guess we can build anything mac specific there. Here is my config - https://github.com/can3p/perlotto/blob/master/.travis.yml

I have another project that can be useful, in case it's possible to build nEXT using only dependencies delivered by homebrew - https://github.com/can3p/cl-brewer

If we do that it build step should become really easy for everyone.

**Comment by asimpson** [comment]
@jmercouris Yep I started following those and got stuck [here](https://github.com/nEXT-Browser/nEXT/tree/master/next#installing-eql5-library--executable-embedded-qt-lisp).

`make` errored with this message:
```
Undefined symbols for architecture x86_64:
  "QSGTexture::bind()", referenced from:
      LSGDynamicTexture::bind() in moc__q_classes.o
  "QSGTexture::hasMipmaps() const", referenced from:
      LSGDynamicTexture::hasMipmaps() const in moc__q_classes.o
  "QSGTexture::textureSize() const", referenced from:
      LSGDynamicTexture::textureSize() const in moc__q_classes.o
  "QSGTexture::hasAlphaChannel() const", referenced from:
      LSGDynamicTexture::hasAlphaChannel() const in moc__q_classes.o
  "QSGTexture::textureId() const", referenced from:
      LSGDynamicTexture::textureId() const in moc__q_classes.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../libeql5_quick.dylib] Error 1```

**Comment by jmercouris** [comment]
Hi Adam,

Thank you very much for your report! I think there are some minor issues with EQL and the quick module at this time. As QT evolves, EQL has to evolve to match new APIs etc, sometimes it has problems on OSX and not Linux due to parity issues. It is of course a WIP :)

In the meantime, please try commenting out all modules from eql5.pro that are not webkit, then `make clean`, then restart the process to build EQL. This should 99% work.

Also, yesterday the EQL maintainer emailed me to tell me that I can weak link to previous versions of OSX, so it should be possible for me to release a version for Sierra as well as long as I change the line in `next.pro`

`QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.13`

to

`QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.12`

After that, I can simply recompile, and upload the new binary for you all to try out,

Thanks,

-John

**Comment by jmercouris** [comment]
Hi Dimitry,

that's a really good idea! I'd like to set up some reliable form of build system. We'll have to look into exactly how this can be done. I think before we do that though, we should probably fix some issues within EQL and ECL which need to be patched for successful building. I'm not really familiar with Travis or an automated build system, is it basically like a provisioning system that just then runs some commands? If so, we can fork and patch ECL and EQL with some changes made for the build server.

**Comment by jmercouris** [comment]
@asimpson 

Please try re-downloading the DMG as I've uploaded a new one, this one should work on your system as I've linked it against Sierra :)

**Comment by jmercouris** [comment]
Tested on Sierra, confirmed working! Thank you for your patience!

**Comment by asimpson** [comment]
@jmercouris yep, thank you so much!

**Comment by jmercouris** [comment]
No problem! Glad to help! :)

**Comment by can3p** [comment]
@jmercouris Issue is closed but I'll answer you anyway. From what I see, a travis config contains script field among the others, which points to the any sort of script that has to be executed in order to produce the build and the file field in the deploy section contains a path to a file that is produced in the end. travis runs builds on every commit, and luckily there is a way to take that file and append it to release of the project on github. Having said that I don't see any problem with applying patches both to eql and ecl as long as it can be done inside of the build script. Since this issue is closed, let's create another one and we can investigate more in this direction in case you're interested.

**Comment by jmercouris** [comment]
@can3p Ok sounds good, please create it in the new repository, specifically dedicated to this located at: https://github.com/nEXT-Browser/Environment/issues
