### ISSUE TITLE
Release for Ubuntu

### ISSUE THREAD

**Issue by jajoosam** [nEXT-Browser/nEXT#6]
A .Deb would be very helpful ☺

**Comment by deadtrickster** [comment]
This is my error on ubuntu
```
$ eql5 make
$ ./next 

Condition of type: UNDEFINED-FUNCTION
The function ASDF/SYSTEM::SYSTEM-RELATIVE-PATHNAME is undefined.
No restarts available.

Top level in: #<process TOP-LEVEL>.
```

**Comment by jmercouris** [comment]
@deadtrickster 

Hey, that is because of QURI, you need to uninstall QURI: https://groups.google.com/forum/#!topic/quicklisp/CvB3mwsL7l4

And then bring in the new dependency PURI (same as QURI, but 100% portable)

You may also want to pull the latest version of the repository and retry the make, please let me know how that goes!

**Comment by jmercouris** [comment]
@jajoosam 

I agree! I also have no knowledge on how to do this :D any help would be greatly appreciated!

**Comment by jmercouris** [comment]
I'm temporarily closing this issue, as the packaging will change significantly with a new release coming shortly.

**Comment by dvdmuckle** [comment]
Ubuntu packaging is kind of a pain, but, packaging a .rpm is pretty easy, and once that's done, the .rpm can be converted to a .deb.
